import { saveAs } from 'file-saver';
import * as XLSX from 'xlsx';

// Excel
export function exportExcelDummy(doc) {
    const data = [
        { Field: 'Document Name', Value: doc.name },
        { Field: 'Date', Value: doc.date },
        { Field: 'Size', Value: doc.size },
        { Field: 'Confidence', Value: doc.confidence || 'N/A' },
        { Field: 'Results in English', Value: 'Sample extracted English text goes here...' },
        { Field: 'Results in Japanese', Value: 'サンプルの抽出された日本語テキスト...' },
        { Field: 'Generated By', Value: 'OCR System' },
    ];
    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'OCR Data');
    const wbout = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
    saveAs(new Blob([wbout], { type: 'application/octet-stream' }), `${doc.name}.xlsx`);
}

// PDF
export function exportPdfDummy(doc) {
    window.print();
}

// Text(TXT)
export function exportTextDummy(doc) {
    const text = `
               Document Name: ${doc.name}
               Date: ${doc.date}
               Size: ${doc.size}
               Confidence: ${doc.confidence || 'N/A'}
               Results in English:
               Sample extracted English text goes here...
               Results in Japanese:
               サンプルの抽出された日本語テキスト...
               Generated by OCR System
               `;
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, `${doc.name}.txt`);
}
